// This file was auto-generated by ML.NET Model Builder. 

using System;
using PredictMeML.Model;

namespace PredictMeML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                F_boxer_age = 28F,
                F_boxer_ranking = 2F,
                S_boxer_ranking = 24F,
                S_boxer_age = 33F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual MatchRounds with predicted MatchRounds from sample data...\n\n");
            Console.WriteLine($"F_boxer_age: {sampleData.F_boxer_age}");
            Console.WriteLine($"F_boxer_ranking: {sampleData.F_boxer_ranking}");
            Console.WriteLine($"S_boxer_ranking: {sampleData.S_boxer_ranking}");
            Console.WriteLine($"S_boxer_age: {sampleData.S_boxer_age}");
            Console.WriteLine($"\n\nPredicted MatchRounds: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
